---

- name: Restart SSH
  become: true
  systemd:
    name: "{{ 'sshd' if ansible_facts['distribution'] == 'Archlinux' else 'ssh' }}"
    state: restarted

- name: Restart Fail2ban
  become: true
  systemd:
    name: fail2ban
    state: restarted
    enabled: true
