---
app_name: 'photoview'
app_env:
    PHOTOVIEW_DATABASE_DRIVER: 'mysql'
    PHOTOVIEW_LISTEN_PORT: '8000'
    PHOTOVIEW_MEDIA_CACHE: '/app/cache'
    #PHOTOVIEW_LISTEN_IP: '0.0.0.0'
    PHOTOVIEW_MYSQL_URL: "{{ mariadb_admin_user }}:{{ mariadb_admin_password }}@tcp({{ lookup('dig', ansible_host) }}:3308)/photoview"
app_image: 'docker.io/viktorstrate/photoview'
app_ports: 8000
app_volumes:
     - "{{ volume_root_dir}}/photoview/api_cache:/app/cache"
