node{
  stage('Fetch code') {
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/itaifrenkel/java-hello-world-webapp/']]]) 
  }
  stage('Build') {
       sh 'mvn clean package'
  }
  stage('Test'){
      sh 'mvn test'
  }
  stage('Deploy to docker') {
     sh  'sudo docker build -t apache-$BUILD_NUMBER   -f apache1 .'
      sh 'sudo docker run -d --name webproj -p 80:80 -t apache-$BUILD_NUMBER'
  }
}
